server:
  address: localhost
  port: 8080

spring:
  profiles:
    group:
      local: aws, korea
      dev: aws, korea
      stage: aws, korea
      proudect: aws, korea
  jpa:
    # API 호출 시, SQL 문 콘솔에 출력
    show-sql: true
    # DDL 정의 시 DB의 고유의 기능 사용
    generate-ddl: true
    # MariaDB 상세지정
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        # 쿼리 정렬 옵션
        format_sql: true
  # MariaDB 설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url:
    username:
    password:
    hikari:
      jdbc-url:

# AWS 설정
aws:
  region: ap-northeast-2
  dynamodb:
    table:
      music: music

# MyBatis 설정
mybatis:
  mapper-locations: mybatis/**/*.xml