server:
  address: localhost
  port: 8080

spring:
  jpa:
    # API 호출 시, SQL 문 콘솔에 출력
    show-sql: true
    # DDL 정의 시 DB의 고유의 기능 사용
    generate-ddl: true
    # MariaDB 상세지정
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # MariaDB 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://nobleway.clz9qjdtgrkx.ap-northeast-2.rds.amazonaws.com/nobleway?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: rhkvqkq1990!
